import { useState, useEffect } from 'react';
import { useApi } from '../../hooks/useApi';
import { Modal, Empty, fmtDate } from '../../components/UI';

function generateReportHTML(report) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <title>Medical Report — ${report.patientName}</title>
  <style>
    @media print { @page { margin: 20mm; } }
    body{font-family:'Segoe UI',Arial,sans-serif;max-width:800px;margin:40px auto;padding:32px;color:#1a1a2e;line-height:1.6}
    .header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #1b4332;padding-bottom:20px;margin-bottom:24px}
    .brand{font-size:1.5rem;font-weight:700;color:#1b4332}
    .brand small{display:block;font-size:.73rem;font-weight:400;color:#6b6558;margin-top:2px}
    .meta{text-align:right;font-size:.82rem;color:#6b6558}
    .meta strong{color:#1a1a2e;display:block;font-size:.95rem;margin-bottom:3px}
    .badge{display:inline-block;background:#d8f3dc;color:#1b4332;padding:4px 12px;border-radius:20px;font-size:.73rem;font-weight:700;margin-top:4px}
    .info-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:24px;background:#fdf8f0;border:1px solid #e8ddd0;padding:18px;border-radius:10px}
    .info-item label{font-size:.68rem;text-transform:uppercase;letter-spacing:.07em;color:#6b6558;display:block;margin-bottom:3px}
    .info-item strong{font-size:.9rem;color:#1a1a2e}
    .section{margin-bottom:22px}
    .section h3{font-size:.78rem;text-transform:uppercase;letter-spacing:.08em;color:#6b6558;margin-bottom:10px;padding-bottom:6px;border-bottom:2px solid #e8ddd0;display:flex;align-items:center;gap:8px}
    .section-body{font-size:.9rem;white-space:pre-wrap;background:#f0e8d8;padding:14px 16px;border-radius:8px;border-left:3px solid #1b4332;line-height:1.7}
    .followup{background:#d8f3dc;border:1px solid #95d5b2;border-radius:10px;padding:14px 16px;margin-top:8px}
    .followup-date{font-weight:700;color:#1b4332;font-size:.95rem}
    .followup-note{color:#2d6a4f;font-size:.84rem;margin-top:4px}
    .footer{margin-top:36px;padding-top:16px;border-top:1px solid #e8ddd0;display:flex;justify-content:space-between;align-items:flex-end;font-size:.77rem;color:#9e917e}
    .sig-box{text-align:right}
    .sig-line{width:180px;border-top:1px solid #1a1a2e;padding-top:5px;font-size:.8rem;color:#1a1a2e;font-weight:600;margin-left:auto}
    .sig-label{font-size:.7rem;color:#9e917e;margin-top:2px}
  </style></head><body>
  <div class="header">
    <div>
      <div class="brand">Meridian Health<small>Integrated Clinical Management Platform</small></div>
    </div>
    <div class="meta">
      <strong>Medical Report</strong>
      Report Date: ${fmtDate(report.date)}<br/>
      <span class="badge">Confidential · Patient Copy</span>
    </div>
  </div>
  <div class="info-grid">
    <div class="info-item"><label>Patient Name</label><strong>${report.patientName || '—'}</strong></div>
    <div class="info-item"><label>Patient ID</label><strong>#${report.patientId || '—'}</strong></div>
    <div class="info-item"><label>Consulting Doctor</label><strong>${report.doctorName || '—'}</strong></div>
    <div class="info-item"><label>Department</label><strong>${report.department || '—'}</strong></div>
    <div class="info-item"><label>Visit Date</label><strong>${fmtDate(report.appointmentDate)}</strong></div>
    <div class="info-item"><label>Reason for Visit</label><strong>${report.reason || '—'}</strong></div>
  </div>
  ${report.diagnosis    ? `<div class="section"><h3>🩺 Diagnosis</h3><div class="section-body">${report.diagnosis}</div></div>` : ''}
  ${report.prescription ? `<div class="section"><h3>💊 Prescription</h3><div class="section-body">${report.prescription}</div></div>` : ''}
  ${report.testResults  ? `<div class="section"><h3>🔬 Test Results &amp; Investigations</h3><div class="section-body">${report.testResults}</div></div>` : ''}
  ${report.notes        ? `<div class="section"><h3>📋 Clinical Notes</h3><div class="section-body">${report.notes}</div></div>` : ''}
  ${report.followUpDate ? `<div class="section"><h3>📅 Follow-Up</h3><div class="followup"><div class="followup-date">${fmtDate(report.followUpDate)}</div>${report.followUpNotes ? `<div class="followup-note">${report.followUpNotes}</div>` : ''}</div></div>` : ''}
  <div class="footer">
    <div>This report is computer-generated by Meridian Health.<br/>Issued on ${fmtDate(report.submittedAt || report.date)}. Keep for your records.</div>
    <div class="sig-box">
      <div class="sig-line">${report.doctorName || 'Consulting Doctor'}</div>
      <div class="sig-label">Consulting Physician, Meridian Health</div>
    </div>
  </div>
  </body></html>`;
}

export default function PatientReports() {
  const api = useApi();
  const [reports,    setReports]    = useState([]);
  const [appts,      setAppts]      = useState([]);
  const [viewModal,  setViewModal]  = useState(null);

  useEffect(() => {
    api.getAppointments().then(setAppts);
    try {
      const stored = JSON.parse(localStorage.getItem('doc_reports') || '[]');
      setReports(stored);
    } catch { setReports([]); }
  }, []);

  function download(report) {
    const win = window.open('', '_blank', 'width=900,height=700');
    win.document.write(generateReportHTML(report));
    win.document.close();
    win.onload = () => win.print();
  }

  function downloadAppointmentSummary(appt) {
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
    <title>Appointment Summary</title>
    <style>
      body{font-family:'Segoe UI',Arial,sans-serif;max-width:700px;margin:40px auto;padding:32px;color:#1a1a2e}
      .header{border-bottom:3px solid #1b4332;padding-bottom:16px;margin-bottom:20px}
      .brand{font-size:1.4rem;font-weight:700;color:#1b4332}
      h2{font-size:1rem;margin-bottom:16px;color:#1b4332}
      .grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;background:#fdf8f0;padding:16px;border-radius:10px;border:1px solid #e8ddd0}
      .item label{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;color:#6b6558;display:block}
      .item strong{font-size:.9rem}
      .badge{display:inline-block;background:#d8f3dc;color:#1b4332;padding:3px 10px;border-radius:20px;font-size:.72rem;font-weight:700}
      .footer{margin-top:30px;font-size:.75rem;color:#9e917e;border-top:1px solid #e8ddd0;padding-top:12px}
    </style></head><body>
    <div class="header"><div class="brand">Meridian Health</div><small style="color:#6b6558">Integrated Clinical Management Platform</small></div>
    <h2>Appointment Summary</h2>
    <div class="grid">
      <div class="item"><label>Patient</label><strong>${appt.patientName || '—'}</strong></div>
      <div class="item"><label>Doctor</label><strong>${appt.doctorName || '—'}</strong></div>
      <div class="item"><label>Department</label><strong>${appt.department || '—'}</strong></div>
      <div class="item"><label>Date</label><strong>${fmtDate(appt.appointmentDate)}</strong></div>
      <div class="item"><label>Time</label><strong>${(appt.appointmentTime || '').slice(0,5)}</strong></div>
      <div class="item"><label>Status</label><span class="badge">${appt.status}</span></div>
      <div class="item" style="grid-column:1/-1"><label>Reason</label><strong>${appt.reason || '—'}</strong></div>
    </div>
    <div class="footer">Generated by Meridian Health · ${new Date().toLocaleDateString('en-IN', { day:'numeric',month:'long',year:'numeric' })}</div>
    </body></html>`;
    const win = window.open('', '_blank', 'width=800,height=600');
    win.document.write(html);
    win.document.close();
    win.onload = () => win.print();
  }

  const completedAppts = appts.filter(a => a.status === 'Completed');

  return (
    <div>
      {/* Stats */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 14, marginBottom: 20 }}>
        {[
          { label: 'Medical Reports',      val: reports.length,          color: 'var(--forest)', icon: '📄' },
          { label: 'Completed Visits',     val: completedAppts.length,   color: 'var(--sage)',   icon: '✅' },
          { label: 'Appointments Total',   val: appts.length,            color: 'var(--blue)',   icon: '📅' },
        ].map(s => (
          <div key={s.label} style={{
            background: 'var(--white)', border: '1.5px solid var(--border)',
            borderRadius: 12, padding: '16px 20px',
            display: 'flex', gap: 14, alignItems: 'center',
            boxShadow: 'var(--shadow-sm)',
          }}>
            <div style={{ fontSize: '1.8rem' }}>{s.icon}</div>
            <div>
              <div style={{ fontSize: '1.65rem', fontWeight: 700, color: s.color, lineHeight: 1 }}>{s.val}</div>
              <div style={{ fontSize: '.74rem', color: 'var(--muted)', marginTop: 3 }}>{s.label}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Medical reports from doctors */}
      <div className="card" style={{ marginBottom: 20 }}>
        <div className="card-head">
          <h3>Medical Reports from Doctors</h3>
          <span style={{ fontSize: '.8rem', color: 'var(--muted)' }}>{reports.length} report{reports.length !== 1 ? 's' : ''}</span>
        </div>
        <div className="card-body" style={{ padding: 0 }}>
          {reports.length === 0 ? (
            <div style={{ padding: 40, textAlign: 'center', color: 'var(--muted)' }}>
              <div style={{ fontSize: '2.5rem', marginBottom: 10 }}>📋</div>
              <div style={{ fontSize: '.88rem' }}>No medical reports yet. Reports appear here after your doctor submits them.</div>
            </div>
          ) : reports.map((r, i) => (
            <div key={r.appointmentId} style={{
              display: 'flex', alignItems: 'center', gap: 16, padding: '16px 22px',
              borderBottom: i < reports.length - 1 ? '1px solid var(--stone)' : 'none',
            }}>
              {/* Icon */}
              <div style={{
                width: 48, height: 48, borderRadius: 12,
                background: 'linear-gradient(135deg, var(--forest), var(--moss))',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: '1.4rem', flexShrink: 0,
              }}>
                📄
              </div>

              {/* Info */}
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 700, fontSize: '.92rem', marginBottom: 2 }}>
                  Medical Report — {fmtDate(r.date)}
                </div>
                <div style={{ fontSize: '.76rem', color: 'var(--muted)', marginBottom: 6 }}>
                  {r.doctorName} · {r.department}
                  {r.appointmentDate && ` · Visit: ${fmtDate(r.appointmentDate)}`}
                </div>
                <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {r.diagnosis && (
                    <span style={{ background: 'var(--sand)', padding: '2px 9px', borderRadius: 20, fontSize: '.7rem', color: 'var(--ink)', border: '1px solid var(--stone)' }}>
                      Dx: {r.diagnosis.slice(0, 40)}{r.diagnosis.length > 40 ? '…' : ''}
                    </span>
                  )}
                  {r.followUpDate && (
                    <span style={{ background: '#d8f3dc', padding: '2px 9px', borderRadius: 20, fontSize: '.7rem', color: '#1b4332', border: '1px solid #95d5b2' }}>
                      Follow-up: {fmtDate(r.followUpDate)}
                    </span>
                  )}
                </div>
              </div>

              {/* Actions */}
              <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
                <button className="btn btn-outline btn-sm" onClick={() => setViewModal(r)}>View</button>
                <button className="btn btn-sage btn-sm" onClick={() => download(r)}>⬇ Download</button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Appointment summaries */}
      <div className="card">
        <div className="card-head">
          <h3>Appointment Summaries</h3>
          <span style={{ fontSize: '.8rem', color: 'var(--muted)' }}>Download any visit summary</span>
        </div>
        <div className="card-body" style={{ padding: 0 }}>
          {appts.length === 0 ? (
            <div style={{ padding: 40 }}><Empty text="No appointments yet" /></div>
          ) : [...appts]
            .sort((a, b) => (b.appointmentDate||'').localeCompare(a.appointmentDate||''))
            .map((a, i) => {
              const STATUS_COLOR = {
                Completed: { bg:'#d8f3dc', color:'#1b4332', border:'#95d5b2' },
                Scheduled: { bg:'#eaf4fb', color:'#1a5276', border:'#aed6f1' },
                'Checked-In':{ bg:'#fef9e7', color:'#7d6608', border:'#f9e79f' },
                'In-Progress':{ bg:'#d8f3dc', color:'#1b4332', border:'#95d5b2' },
                Cancelled: { bg:'#fdf2f2', color:'#7b241c', border:'#fadbd8' },
              };
              const sc = STATUS_COLOR[a.status] || {};
              return (
                <div key={a.appointmentId} style={{
                  display: 'flex', alignItems: 'center', gap: 14,
                  padding: '13px 22px',
                  borderBottom: i < appts.length - 1 ? '1px solid var(--stone)' : 'none',
                }}>
                  <div style={{
                    minWidth: 48, textAlign: 'center', padding: '7px 4px',
                    background: 'var(--sand)', borderRadius: 10, flexShrink: 0,
                  }}>
                    <div style={{ fontSize: '.6rem', color: 'var(--muted)', textTransform: 'uppercase' }}>
                      {new Date(a.appointmentDate || Date.now()).toLocaleDateString('en-IN', { month:'short' })}
                    </div>
                    <div style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--forest)', lineHeight: 1 }}>
                      {new Date(a.appointmentDate || Date.now()).getDate()}
                    </div>
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 600, fontSize: '.88rem' }}>{a.doctorName}</div>
                    <div style={{ fontSize: '.74rem', color: 'var(--muted)' }}>
                      {a.department} · {a.reason || '—'}
                    </div>
                  </div>
                  <span style={{
                    padding: '3px 10px', borderRadius: 20, fontSize: '.7rem', fontWeight: 600,
                    background: sc.bg, color: sc.color, border: `1px solid ${sc.border}`,
                  }}>
                    {a.status}
                  </span>
                  <button className="btn btn-outline btn-sm" onClick={() => downloadAppointmentSummary(a)}>
                    ⬇ Summary
                  </button>
                </div>
              );
            })}
        </div>
      </div>

      {/* View Report Modal */}
      {viewModal && (
        <Modal title={`Medical Report — ${fmtDate(viewModal.date)}`} onClose={() => setViewModal(null)}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 18 }}>
            {[
              { label:'Doctor',     val: viewModal.doctorName || '—' },
              { label:'Department', val: viewModal.department || '—' },
              { label:'Visit Date', val: fmtDate(viewModal.appointmentDate) },
              { label:'Report Date',val: fmtDate(viewModal.date) },
            ].map(f => (
              <div key={f.label} style={{ background:'var(--sand)', borderRadius:9, padding:'10px 13px' }}>
                <div style={{ fontSize:'.7rem', color:'var(--muted)', marginBottom:2 }}>{f.label}</div>
                <div style={{ fontWeight:600, fontSize:'.87rem' }}>{f.val}</div>
              </div>
            ))}
          </div>
          {[
            { label:'🩺 Diagnosis',       val: viewModal.diagnosis },
            { label:'💊 Prescription',    val: viewModal.prescription },
            { label:'🔬 Test Results',    val: viewModal.testResults },
            { label:'📋 Clinical Notes',  val: viewModal.notes },
          ].filter(f => f.val).map(f => (
            <div key={f.label} style={{ marginBottom: 14 }}>
              <div style={{ fontSize:'.72rem', color:'var(--muted)', textTransform:'uppercase', letterSpacing:'.07em', marginBottom:6, fontWeight:700 }}>
                {f.label}
              </div>
              <div style={{ background:'var(--sand)', borderRadius:9, padding:'11px 13px', fontSize:'.85rem', whiteSpace:'pre-wrap', lineHeight:1.65, borderLeft:'3px solid var(--sage)' }}>
                {f.val}
              </div>
            </div>
          ))}
          {viewModal.followUpDate && (
            <div style={{ background:'var(--mint)', border:'1px solid #95d5b2', borderRadius:10, padding:'12px 14px', marginBottom:16 }}>
              <div style={{ fontWeight:700, color:'var(--forest)', marginBottom:2 }}>
                📅 Follow-up: {fmtDate(viewModal.followUpDate)}
              </div>
              {viewModal.followUpNotes && (
                <div style={{ fontSize:'.83rem', color:'var(--moss)' }}>{viewModal.followUpNotes}</div>
              )}
            </div>
          )}
          <div className="form-actions">
            <button className="btn btn-outline" onClick={() => setViewModal(null)}>Close</button>
            <button className="btn btn-sage" onClick={() => download(viewModal)}>⬇ Download PDF</button>
          </div>
        </Modal>
      )}
    </div>
  );
}
